### PR TITLE
ScenarioEditor: basic scenario tagging ui scaffold.

### PR DESCRIPTION
**Pull request by rwaldron**
image

This is just a basic sketch out for what needs to be done to complete this feature once the API is updated. Nothing presently blocking this and changes can/should be made in the follow up that @evmiguel will producing.

### CODE REVIEW

**Comment by rwaldron** [comment]
Rebased.

**Comment by ktbee** [comment]
Looking real good! One aesthetic request though: 

can we make the title and description column wider than the categories column? And move it to the lefthand side?

Since categories is just a dropdown, it doesn't seem to need more editing space than the text boxes. Also, with the categories dropdown on the left, it will consistent with the slides dropdown location.

**Comment by ktbee** [comment]
Also just realized I wasn't asked to review this one, but now you have my two cents anyways! :p

**Comment by rwaldron** [comment]
@ktbee 

> And move it to the lefthand side?

I think this will be strange when the user creates a new Moment and the Title and Description fields shift rightward to allow the Category and Topic dropdowns to appear on the left.

**Pull request merged**
