### PR TITLE
Editor: Clicking "Create a moment" from the Editor produces a blank project

### PR DESCRIPTION
**Pull request by rwaldron**
Fixes https://app.asana.com/0/1127815256483386/1145881120386969/f

### CODE REVIEW

**Comment by rwaldron** [comment]
It's possible that this fix created another bug. I've noticed that creating a new moment won't move to the slide editor and there is an error message: 

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Editor (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer
```

**Comment by ktbee** [comment]
w0000 I think we finally got it! What do you think of my latest commit with a NewScenario wrapper @rwaldron ?

**Comment by rwaldron** [comment]
> What do you think of my latest commit with a NewScenario wrapper

As demonstrated by my celebration yesterday, I love it

**Comment by rwaldron** [comment]
I enabled "Rebase and Merge" for this PR because both commits work, however the second is a much better and more correct approach. I didn't want to lose @ktbee's commit in the squash

**Pull request merged**
