### PR TITLE
Editor message component

### PR DESCRIPTION
**Pull request by ktbee**
@gnarf @rwaldron here is my PR for adding a re-usable component for displaying messages in the editor. It ended up being a little more complicated than I had hoped because I needed to switch to Semantic UI's `Menu` component in order to have a right-aligned string next to the tabs. So some of these changes are re-creating the builtin display logic we used to get for free with the `Tab` component. 

Another note, I switched to using `this.state.scenarioId` or `this.props.match.params.id`  instead of `this.state.isNewScenario` because state didn't always seem to be mounted when I needed it.

Let me know what you think and if you have any questions!

### CODE REVIEW

**Comment by rwaldron** [comment]
This may be unrelated, but when I'm editing a slide and click the "Delete" tab, I see this warning in the console: 

```
backend.js:6 Warning: Failed prop type: Invalid prop `name` of value `trash alternate outline icon` supplied to `Icon`.

Instead of `trash alternate outline icon`, did you mean:
  - trash alternate outline
  - trash alternate
  - list alternate outline

    in Icon (created by Button)
    in Button (created by SlideEditor)
    in div (created by Segment)
    in Segment (created by TabPane)
    in TabPane (created by Tab)
    in div (created by Tab)
    in Tab (created by SlideEditor)
    in div (created by GridRow)
    in GridRow (created by SlideEditor)
    in div (created by GridColumn)
    in GridColumn (created by SlideEditor)
    in div (created by Grid)
    in Grid (created by SlideEditor)
    in SlideEditor (created by Slides)
    in div (created by GridColumn)
    in GridColumn (created by Slides)
    in div (created by Grid)
    in Grid (created by Slides)
    in div (created by Container)
    in Container (created by Slides)
    in Slides
    in div (created by Editor)
    in div (created by Editor)
    in Editor (created by Context.Consumer)
    in Route (created by Routes)
    in div (created by Routes)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Routes)
    in Routes
    in Provider
r @ backend.js:6
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:82
validatePropTypes @ react.development.js:1885
createElementWithValidation @ react.development.js:2069
React$$1.createElement @ react-hot-loader.development.js:2877
createShorthand @ factories.js:149
eval @ factories.js:172
render @ Button.js:208
finishClassComponent @ react-dom.development.js:18407
updateClassComponent @ react-dom.development.js:18360
beginWork$1 @ react-dom.development.js:20108
beginWork$$1 @ react-dom.development.js:25708
performUnitOfWork @ react-dom.development.js:24638
workLoopSync @ react-dom.development.js:24614
performSyncWorkOnRoot @ react-dom.development.js:24182
eval @ react-dom.development.js:12238
unstable_runWithPriority @ scheduler.development.js:815
runWithPriority$2 @ react-dom.development.js:12188
flushSyncCallbackQueueImpl @ react-dom.development.js:12233
flushSyncCallbackQueue @ react-dom.development.js:12221
discreteUpdates$1 @ react-dom.development.js:24365
discreteUpdates @ react-dom.development.js:1486
dispatchDiscreteEvent @ react-dom.development.js:5926
```

**Comment by rwaldron** [comment]
@ktbee can you clarify something for me: is this limited to Slide component status? For example, we couldn't use this component to notify the user that they are in offline mode (assuming that we may one day be asked to support offline slide authoring). If that's the case, then this patch satisfies the current need, but we'll want to create a future work item to uplift the mechanism from this component and make it globally available to all components in the application.

**Comment by rwaldron** [comment]
I just found a "bug": there is no notification when a new slide is added.

**Comment by rwaldron** [comment]
> I just found a "bug": there is no notification when a new slide is added.

@ktbee and I pair reviewed and discussed this in person and agreed that it's more valuable to land the feature ahead of today's user tests, than to wait for a minor change to be implemented.

**Comment by ktbee** [comment]
> @ktbee can you clarify something for me: is this limited to Editor component status? For example, we couldn't use this component to notify the user that they are in offline mode (assuming that we may one day be asked to support offline slide authoring). If that's the case, then this patch satisfies the current need, but we'll want to create a future work item to uplift the mechanism from this component and make it globally available to all components in the application.
> 
> Edit: I think we _could_ use it for the case I described above, ie. "Editor is in offline mode".

I really like your idea @rwaldron of using this component for all messaging! It's not necessarily something we need to limit to the editor.

**Pull request merged**
